[tool.black]
line-length = 88
target-version = ["py39"]
include = "\\.pyi?$"
exclude = """
/(\n    \\.(git|hg|svn)\n  | \\_build\n  | buck-out\n  | build\n  | dist\n)/
"""

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [
  ".git",
  "__pycache__",
  "build",
  "dist",
  "venv",
  ".venv"
]
